config/routes.rb
Pixtr::Application.routes.draw do
  resources :photos
  
  resources :galleries do
    resources :photos
  end

  
  root :to => 'galleries#index'

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base

  validates_presence_of :title, :on => :create, :message => "can't be blank"

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  has_attached_file :image
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates_presence_of :title, :on => :create, :message => "can't be blank"
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Authentication
  protect_from_forgery
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_filter :deny_visitor, :only => [:new, :create]
  
  def index
    @galleries = Gallery.all
    
    respond_to do |format|
      format.html
    end
  end

  def new
    @gallery = Gallery.new
  end
  
  def create
    @gallery = Gallery.new(params[:gallery])

    respond_to do |format|
      if @gallery.save
        format.html { redirect_to @gallery, notice: 'Gallery was successfully created.' }
      else
        format.html { render action: "new" }
     
      end
    end
  end
  
  def show
    @gallery = Gallery.find(params[:id])
  end

  def edit
      @gallery = Gallery.find(params[:id])
    end
  private
  def deny_visitor
    #if signed out redirect
    unless signed_in?
      redirect_to :root, notice: 'Visitors cannot create a gallery'
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @galleries = Gallery.all
    
    respond_to do |format|
      format.html
    end
  end
    
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  
  def new
    @photo = Photo.new
  end
  
  def index
    @photos = Photo.all
    
    respond_to  do |format|
      format.html
    end
  end
  

  def create
    @photo = Photo.new(params[:photo])
    
    @photo.save 
    redirect_to @photo

  end
  
  def show
    @photo = Photo.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photo_helper.rb
module PhotoHelper
end

app/views/galleries/_form.html.erb
<%= form_for(@gallery) do |f| %>
  <% if @gallery.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>

        <ul>
        <% @gallery.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
  
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit "Create Gallery" %>
  </div>
<% end %>

app/views/galleries/edit.html.erb
<%= render 'form' %>

app/views/galleries/index.html.erb
<h1>Pixtr</h1>
<%= link_to "Create Gallery", new_gallery_path %>


<ul>

<% @galleries.each do |gallery| %>
    <li><%= link_to gallery.title, gallery_path(gallery) %></li>
<% end %>
</ul>

app/views/galleries/new.html.erb
<h1>Create a new gallery</h1>

 <%= render 'form'%>
   

app/views/galleries/show.html.erb
<h1>Gallery created successfully</h1>
<div><%= @gallery.title %></div>
<%= link_to "Upload Photo", new_photo_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pixtr</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |key, value| -%>
    <div class="flash <%= key %>"><%= value %></div>
  <% end -%>

  <% if signed_in? %>
    <%= link_to "Sign out", sign_out_path, :method => :delete %>
  <% else %>
    <%= link_to "Sign in", sign_in_path %>
    <%= link_to "Sign up", sign_up_path %>
  <% end %>


<%= yield %>

</body>
</html>

app/views/photos/_form.html.erb
<%= form_for @photo, html: {multipart: true} do |f| %>
<div class="field">
  <%= f.label :name %><br />
  <%= f.text_field :name %>
</div>
<div class="field">
  <%= f.label :image %><br />
  <%= f.file_field :image %>
</div>
<div class="actions">
  <%= f.submit "Upload Photo" %>
</div>
<% end %>

app/views/photos/new.html.erb
<%= render 'form'%>

app/views/photos/show.html.erb
<%= image_tag @photo.image.url %>